### PR TITLE
use createMock instead of deprecated getMock()

### PR DESCRIPTION
**Pull request by OskarStark**
I am targeting this branch, because this is BC.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Error 404 TestCase not found

**Comment by OskarStark** [comment]
Fixed

**Comment by greg0ire** [comment]
> use creteMock insted

Are you having issues with your "a" key?

**Comment by OskarStark** [comment]
> Are you having issues with your "a" key? 

not sure :)

**Comment by jordisala1991** [comment]
Insted -> instead on commit message

**Comment by jordisala1991** [comment]
depreated -> deprecated

**Comment by jordisala1991** [comment]
Thanks @OskarStark

**Pull request merged**
