### PR TITLE
re-arrange default key under page. refs #86

### PR DESCRIPTION
**Pull request by mvhirsch**
Had the same issue as described in #86.
I followed the installation guide, so I think this should fix the problem for others.

### CODE REVIEW

**Comment by OskarStark** [comment]
:+1: thx @mvhirsch

**Comment by mvhirsch** [comment]
Why do the builds fail? It was just a documentation update ...
Can anyone please help me with this?

**Comment by OskarStark** [comment]
this error comes from the sonata core bundle i think

@rande @Soullivaneuh can you please check that

anyway, we should update this bundle to make it compatible with the current SonataCoreBundle

anyway, please merge this PR

**Comment by Soullivaneuh** [comment]
Thank you @mvhirsch.

**Pull request merged**
