### PR TITLE
[MOD] Attributes visibility

### PR DESCRIPTION
**Pull request by Th3Mouk**
https://github.com/sonata-project/SonataSeoBundle/issues/113

### CODE REVIEW

**Comment by core23** [comment]
:-1: There are getters for this

**Comment by Th3Mouk** [comment]
that was i said but why private and not protected ?

**Comment by core23** [comment]
No idea. @rande created the file long time ago...

**Comment by greg0ire** [comment]
Maybe because he read [this](http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html) ?

**Comment by core23** [comment]
When changing the fields to protected, we should remove the same methods for the next major release.

**Comment by Th3Mouk** [comment]
This makes sense my first approach was good. Thx !

**Pull request closed without merging**
