### PR TITLE
Register Symfony Command

### PR DESCRIPTION
**Pull request by gander**
I am targeting this branch, because there is no BC-break.

## Subject

I am adding this code because the command is not automatically registered.

## Changelog
```markdown
### Fixed
+ Register `Sonata\SeoBundle\Command\SitemapGeneratorCommand` via `console.command` tag
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Hey there!

It looks like you did not fill the pull request template properly. Maybe you
were confused, so let me walk you through this step by step.

# Explaining why you target this branch

> I am targeting this branch, because {reason}.

Here, you are supposed to replace `{reason}` with something like:

- "there is a BC-break" if you picked the master branch
- "there is no BC-break" if you picked the stable branch

# Filling the changelog

That one is really important to get right, because it will be used to craft a
release changelog such as [this
one](https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.23.0).
The first thing you need to know about this is that if your pull request is
pedantic, meaning it does not fix a bug for the user, or adds a new feature, it
is not needed. This is typically the case for PRs that fix the build or add
some documentation.

3 important things:

1. Make sure to fill the changelog section with something directed at the end
user, that answers the question "What benefit do I get from upgrading?".
2. Make sure to remove empty sections.
3. Make sure to keep the markdown markup.

**Comment by gander** [comment]
Now is ok?

**Comment by OskarStark** [comment]
> Now is ok?

Yes, i updated your changelog a bit

**Comment by jordisala1991** [comment]
Thank you @gander

**Pull request merged**
