### PR TITLE
Avoid phpstan-return

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by jordisala1991** [comment]
Did you read my last comment on the previous Pr?

**Comment by VincentLanglet** [comment]
> Did you read my last comment on the previous Pr?

Test are fine, so I don't see why it's an issue to have a more precise return type.
In the futur we will have both `return Source` and `: mixed`, that's not a problem

**Review by core23 — APPROVED** [review]

**Comment by jordisala1991** [comment]
I dont see how we will remember the correct type, but it is fine by me

**Comment by VincentLanglet** [comment]
> I dont see how we will remember the correct type, but it is fine by me

I'm not even sure it's important to add `: mixed`.
Since php 7.4, a more precise return typehint can be used, so 
```
public function current(): Source
```
should be valid.

**Review by jordisala1991 — APPROVED** [review]

**Pull request merged**
