### PR TITLE
use Sonata\BlockBundle\Block\Service\AbstractAdminBlockService instead of deprecated Sonata\BlockBundle\Block\BaseBlockService

### PR DESCRIPTION
**Pull request by OskarStark**
I am targetting this branch, because this is BC.

## Changelog

```markdown
### Removed
- use `Sonata\BlockBundle\Block\Service\AbstractAdminBlockService` instead of deprecated `Sonata\BlockBundle\Block\BaseBlockService`
```

### CODE REVIEW

**Comment by greg0ire** [comment]
No need to bump the dependency?

**Comment by OskarStark** [comment]
not sure 😄

**Comment by OskarStark** [comment]
@greg0ire I increased the block-bundle dep to `3.2`, hopefully the `--prefer-lowest` build will be green afterwards!

**Comment by greg0ire** [comment]
I think the last two jobs of the build are no longer useful, are they?

**Comment by OskarStark** [comment]
> I think the last two jobs of the build are no longer useful, are they?

You are right!

**Comment by OskarStark** [comment]
Rebased

**Comment by OskarStark** [comment]
Rebased

**Comment by OskarStark** [comment]
Rebased again

**Comment by OskarStark** [comment]
Rebased again, please merge when green @greg0ire

**Comment by greg0ire** [comment]
Please ping me when green.

**Comment by OskarStark** [comment]
@greg0ire can you help?
https://travis-ci.org/sonata-project/SonataSeoBundle/jobs/197917314

**Comment by greg0ire** [comment]
Imo the issue comes from the fact that phpunit 6 is out

**Comment by OskarStark** [comment]
Rebased

**Comment by core23** [comment]
Thanks @OskarStark

**Comment by Soullivaneuh** [comment]
@OskarStark Deprecation changelog should be on the `Fixed` part.

I updated it for you, please take a look.

**Pull request merged**
