### PR TITLE
Minor composer improvements

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this is BC.

## Subject

- Added missing dependencies
- Increase some deps to avoid long builds

### CODE REVIEW

**Comment by core23** [comment]
How did you find all dependencies?

**Comment by jordisala1991** [comment]
searching on the code for "use Symfony\" and "use Sonata\"

**Comment by kunicmarko20** [comment]
Can you check travis?

**Comment by kunicmarko20** [comment]
Seems that it just timed out, I restarted the build.

**Comment by greg0ire** [comment]
Thanks @jordisala1991 !

**Pull request merged**
