### PR TITLE
Prepare 3.0.0-RC1

### PR DESCRIPTION
**Pull request by core23**
As there is not so much activity around this project, it should be safe to create the first release candidate version.

### CODE REVIEW

**Review by VincentLanglet — DISMISSED** [review]
Phpstan level 8 with strict rules
Psalm level 3
No next major
typehint
final classes (Maybe we could add final to 
https://github.com/sonata-project/SonataSeoBundle/blob/9f3287a72ca2fecb81708f4dc3fa2c69eb474ac1/src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php#L40
too ?)

seems ok to me

**Comment by core23** [comment]
> inal classes (Maybe we could add final to
> 
> https://github.com/sonata-project/SonataSeoBundle/blob/9f3287a72ca2fecb81708f4dc3fa2c69eb474ac1/src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php#L40
> 
> 
> too ?)

Good catch. We don't need this method. I'll fix this with #622

**Comment by jordisala1991** [comment]
Maybe we can avoid rc and go directly for 3.0? If there is no reported issues for the alpha and barely no changes

**Comment by VincentLanglet** [comment]
> > inal classes (Maybe we could add final to
> > https://github.com/sonata-project/SonataSeoBundle/blob/9f3287a72ca2fecb81708f4dc3fa2c69eb474ac1/src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php#L40
> > 
> > too ?)
> 
> Good catch. We don't need this method. I'll fix this with #622

Also, HomepageBreadcrumbBlockService is overriding `getMenu` to do the same implementation.
Can't `getMenu` become private ? (and I see no reason to create another method `getRootMenu` then)

If we decide to make `getMenu` non-final and protected to allow an override, then `getMenuOptions` should be private too. (But still I see no reason to have a `getRootMenu` method)

**Comment by core23** [comment]
Please review @sonata-project/contributors. I'll plan to release this tomorrow

**Review by VincentLanglet — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Pull request merged**
