### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by abdellahrk**
## Support Symfony 7

 - 3.x I am targeting this branch, because it's a feature.

## Changelog

```markdown
### Added
- Support for Symfony 7

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi, you still have conflict 
image

You need to rebase your branch with origin/3.x

**Comment by abdellahrk** [comment]
Hello @VincentLanglet, I get this message `Current branch bump-symfony-version-to-7 is up to date.` when I do `git rebase origin/3.x`. Even when I switch to my `3.x` branch and run the same command I get `Current branch 3.x is up to date.` 
Please help me resolve it. Can I switch to a new branch and do all the changes there and send a pull request again?
Thank you.

**Comment by VincentLanglet** [comment]
I rebased https://github.com/sonata-project/SonataSeoBundle/pull/733

**Comment by abdellahrk** [comment]
Thank you @VincentLanglet

**Pull request closed without merging**
