### PR TITLE
3.8.0

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
If you want to try to add SF 7 support on SonataPageBundle @eerison, I'll be curious to know if there is a blocker since SeoBundle support SF7 now.

**Comment by eerison** [comment]
> If you want to try to add SF 7 support on SonataPageBundle @eerison, I'll be curious to know if there is a blocker since SeoBundle support SF7 now.

Hey @VincentLanglet 

I guess we can wait someone provide support for sf7.

Atm I can't do this  :/

**Comment by abdellahrk** [comment]
@eerison Symfony 7 is supported. See #733

**Comment by eerison** [comment]
> @eerison Symfony 7 is supported. See #733

Hello @abdellahrk 

I was talking about other bundle that use `SonataSeoBundle`.

https://github.com/sonata-project/SonataPageBundle

**Pull request merged**
