### PR TITLE
Feature support symfony3 assetic

### PR DESCRIPTION
**Pull request by anboo**
Symfony assetic bundle conflict if twig/twig < 1.27 version

### CODE REVIEW

**Comment by greg0ire** [comment]
40 commits… you need to rebase interactively on 2.x, and get rid of all the commits that are not yours, and then force push.

**Comment by anboo** [comment]
I've done.

**Comment by greg0ire** [comment]
> Symfony assetic bundle conflict if twig/twig < 1.27 version

So… composer must try to use 1.27 or higher then right? What's preventing it to do so?

**Comment by anboo** [comment]
Composer must try use twig/twig >= 1.27 because of assetic bundle throw error if twig < 1.27 and it not working for symfony 3.2

**Comment by greg0ire** [comment]
> assetic bundle throw error if twig < 1.27 

Then assetic bundle should be fixed so that twig < 1.27 can't be installed with it, right?

**Comment by anboo** [comment]
please check for me
if I try install sonata seo bundle for symfony 3.2 this printed me follow error:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove symfony/assetic-bundle v2.8.1
>     - Conclusion: don't install symfony/assetic-bundle v2.8.1
>     - twig/twig v1.12.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.12.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.12.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.12.3 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.13.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.13.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.13.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.14.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.14.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.14.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.15.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.15.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.16.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.16.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.16.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.16.3 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.17.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.18.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.18.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.18.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.19.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.20.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.21.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.21.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.21.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.22.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.22.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.22.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.22.3 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.23.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.23.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.23.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.23.3 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.24.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.24.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.24.2 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.25.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.26.0 conflicts with symfony/assetic-bundle[v2.8.1].
>     - twig/twig v1.26.1 conflicts with symfony/assetic-bundle[v2.8.1].
>     - Installation request for symfony/assetic-bundle (locked at v2.8.1, required as ^2.8) -> satisfiable by symfony/assetic-bundle[v2.8.1].
>     - Installation request for sonata-project/seo-bundle ^2.1 -> satisfiable by sonata-project/seo-bundle[2.1.0].
>     - Conclusion: don't install twig/twig v2.1.0|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1
>     - Conclusion: remove twig/twig v2.1.0|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1
>     - sonata-project/seo-bundle 2.1.0 requires twig/twig ^1.12 -> satisfiable by twig/twig[v1.12.0, v1.12.1, v1.12.2, v1.12.3, v1.13.0, v1.13.1, v1.13.2, v1.14.0, v1.14.1, v1.14.2, v1.15.0, v1.15.1, v1.16.0, v1.16.1, v1.16.2, v1.16.3, v1.17.0, v1.18.0, v1.18.1, v1.18.2, v1.19.0, v1.20.0, v1.21.0, v1.21.1, v1.21.2, v1.22.0, v1.22.1, v1.22.2, v1.22.3, v1.23.0, v1.23.1, v1.23.2, v1.23.3, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0].
>     - Can only install one of: twig/twig[v1.28.0, v2.1.0].
>     - Can only install one of: twig/twig[v1.28.1, v2.1.0].
>     - Can only install one of: twig/twig[v1.28.2, v2.1.0].
>     - Can only install one of: twig/twig[v1.29.0, v2.1.0].
>     - Can only install one of: twig/twig[v1.30.0, v2.1.0].
>     - Can only install one of: twig/twig[v1.31.0, v2.1.0].
>     - Can only install one of: twig/twig[v1.27.0, v2.1.0].
>     - Installation request for twig/twig (locked at v2.1.0) -> satisfiable by twig/twig[v2.1.0].

**Comment by greg0ire** [comment]
What if you require `twig/twig` `1.27`? Not everyone is using assetic, that's why I'm a bit reluctant to merge this.

**Comment by anboo** [comment]
assetic bundle very popular bundle and all checks with twig >= 1.27 have been passed C:

**Comment by greg0ire** [comment]
I guess it's only a minor, so why not… WDYT @sonata-project/contributors ?

**Comment by Soullivaneuh** [comment]
> Composer must try use twig/twig >= 1.27 because of assetic bundle throw error if twig < 1.27 and it not working for symfony 3.2

The current `^1.12` constraint does allow 1.27 and higher, I don't see why we must change that.

@anboo Could you please paste your full `composer.json`?

**Comment by anboo** [comment]
```
{
    "name": "anboo/.checkout",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.2.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "knplabs/knp-paginator-bundle": "^2.5",
        "sonata-project/admin-bundle": "^3.13",
        "sonata-project/doctrine-orm-admin-bundle": "^3.1",
        "dpn/xml-sitemap-bundle": "^2.1",
        "phpunit/phpunit": "^6.0",
        "symfony/assetic-bundle": "^2.8",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "doctrine/cache": "^1.6"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
          "@symfony-scripts"
        ],
        "post-update-cmd": [
          "@symfony-scripts"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": null
    }
}

```

**Comment by Soullivaneuh** [comment]
The error occur because you already have twig 2.x installed on you project, and when you run:

```
composer require sonata-project/seo-bundle
```

Composer tries to install this dependency **only**, without updating the rest. This is why you have the conflict error.

It seems you can tell to composer to do this at runtime, so you have to run this:

```
composer require sonata-project/seo-bundle --no-update
```

And then:

```
composer update sonata-project/seo-bundle twig/twig
```

And this will work, downgrading twig to 1.x version.

I close this PR because seo-bundle currently does accept any 1.x twig version starting 1.12 and this will not solve your issue.

**Pull request closed without merging**
