### PR TITLE
DevKit updates for 2.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Anything going on here to get SeoBundle Symfony 4.0 compatible? Any help needed?

**Comment by greg0ire** [comment]
Yes. It does not install because the datagrid bundle is not 4.0 compatible because this is not merged yet: https://github.com/Soullivaneuh/php-cs-fixer-styleci-bridge/pull/81
So... finish what you started, I guess?

**Comment by ElectricMaxxx** [comment]
i mentioned this in the PR i wait for you :-p

**Comment by ElectricMaxxx** [comment]
ohh now i realized, that you mean me and my work :-) lool :-)

**Pull request merged**
