### PR TITLE
feat: add Symfony 6 to SeoBundle

### PR DESCRIPTION
**Pull request by Kocal**
## Subject

I am targeting this branch, because it does not contains BC.

- Parts of https://github.com/sonata-project/dev-kit/issues/1675
- dev-kit PR: https://github.com/sonata-project/dev-kit/pull/1739

## Changelog

```markdown
### Added
- Added Symfony 6 support
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
I need to perform a merge from 2.x to 3.x before this one can be merged. I will try to do it today.

**Comment by jordisala1991** [comment]
Can you solve conflicts?

**Comment by Kocal** [comment]
PR rebased!

**Review by jordisala1991 — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks !

**Pull request merged**
