### PR TITLE
Add missing italian translations

### PR DESCRIPTION
**Pull request by gremo**
Add missing italian translations.

### CODE REVIEW

**Comment by core23** [comment]
Please run `make lint` to fix the PR.

**Comment by gremo** [comment]
I'm under Windows and I don't know how to run that command. Can you give me a clue?

**Comment by core23** [comment]
@greg0ire Can you help? You created the `lint`ing stuff

**Comment by greg0ire** [comment]
[Install xmllint](http://stackoverflow.com/questions/19546854/installing-xmllint#21227833), then run it on your file just like `make lint` does. Alternatively, just apply [this diff](https://travis-ci.org/sonata-project/SonataSeoBundle/jobs/194908651#L258)

**Comment by gremo** [comment]
Thank you @greg0ire, done!

**Comment by OskarStark** [comment]
@gremo can you please rebase?

**Comment by gremo** [comment]
@OskarStark done, rebasing + squashing the commits into one. Are you able to merge now?

**Comment by greg0ire** [comment]
Perfect! Thanks @gremo !

**Pull request merged**
