### PR TITLE
Fix deprecated settings method on block service, fix #96

### LINKED ISSUE #96: Fix deprecated settings method on block service
To be done when https://github.com/sonata-project/SonataBlockBundle/pull/204 will be merged.

### PR DESCRIPTION
**Pull request by sagikazarmark**
ping @Soullivaneuh

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
CS failed: https://travis-ci.org/sonata-project/SonataSeoBundle/jobs/82755367#L540

**Comment by sagikazarmark** [comment]
Pushed a fix. Wouldn't it be better to set up scrutinizer to check CS? IMO it would make travis builds faster.

**Comment by Soullivaneuh** [comment]
> Wouldn't it be better to set up scrutinizer to check CS

Scrutinizer is not bloquant with that, but I found another quicker solution under discussion here: https://github.com/sonata-project/SonataAdminBundle/pull/3273

**Comment by sagikazarmark** [comment]
> bloquant

Is that a French word meaning 'blocking'?

What does blocking mean in this context? Mark build as failed? AFAIK scrutinizer creates separate issues for CS discrepancies.

**Comment by Soullivaneuh** [comment]
Yes sorry for the french spawning. :-)

> AFAIK scrutinizer creates separate issues for CS discrepancies.

Yes, but it does not always mark it as failed AFAIK.

StyleCI is especially for php-cs-fixer and it's quicker. :+1:

**Comment by sagikazarmark** [comment]
Great :+1:

**Comment by sagikazarmark** [comment]
CS fixed, can this be merged? Then we will see a nice red line here: sonata-project/SonataBlockBundle#204

**Comment by Soullivaneuh** [comment]
Thank you @sagikazarmark.

**Pull request merged**
