### PR TITLE
Avoided blocks.xml loading when KnpMenuBundle is missing #56

### PR DESCRIPTION
**Pull request by tuRn-x**
After installing SonataSeoBundle in our project, this error popped out :

`The service "sonata.seo.block.breadcrumb.homepage" has a dependency on a non-existent service "knp_menu.menu_provider".`

Actually, KnpMenuBundle is also needed to load the `blocks.xml` file so, since it's optional, it's probably better to avoid to load that file than to add a new dependency.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Could you please add related tests?

**Comment by tuRn-x** [comment]
@Soullivaneuh PR updated thanks to @mremi ;)

**Comment by Soullivaneuh** [comment]
Please fix CS: https://travis-ci.org/sonata-project/SonataSeoBundle/jobs/81810049#L387

**Comment by mremi** [comment]
@tuRn-x To do so, run `make cs` and push the updated file.

**Comment by Soullivaneuh** [comment]
@mremi I let you the final review and merge.

@tuRn-x please remember to squash after fix. :+1:

**Comment by tuRn-x** [comment]
@Soullivaneuh @mremi done !

**Pull request merged**
