### PR TITLE
Add priority for breadcrumb blocks

### LINKED ISSUE #194: Priority for breadcrumb blocks
## Subject

At the moment it is not possible to override a breadcrumb block with the same `context`. This could be fixed by defining a priority.

## Steps to reproduce

Define two breadcrumb services with the `news_post` context.

```xml
        <service id="sonata.news.block.breadcrumb_post" class="Sonata\NewsBundle\Block\Breadcrumb\NewsPostBreadcrumbBlockService">
            <tag name="sonata.block"/>
            <tag name="sonata.breadcrumb"/>
            <argument>news_post</argument>
            <argument>sonata.news.block.breadcrumb_post</argument>
            <argument type="service" id="templating"/>
            <argument type="service" id="knp_menu.menu_provider"/>
            <argument type="service" id="knp_menu.factory"/>
            <argument type="service" id="sonata.news.blog"/>
        </service>

        <service id="custom.news.block.breadcrumb_post" class="Custom\NewsBundle\Block\Breadcrumb\NewsPostBreadcrumbBlockService">
            <tag name="sonata.block"/>
            <tag name="sonata.breadcrumb"/>
            <argument>news_post</argument>
            <argument>custom.news.block.breadcrumb_post</argument>
            <argument type="service" id="templating"/>
            <argument type="service" id="knp_menu.menu_provider"/>
            <argument type="service" id="knp_menu.factory"/>
            <argument type="service" id="sonata.news.blog"/>
        </service>
```

Call the breadcrumb rendern for the `news_post` context in twig template:

```twig
        {{ sonata_block_render_event('breadcrumb', { 'context': 'news_post', 'post': post, 'current_uri': app.request.requestUri }) }}
```

## Expected results

The last defined breadcrumb will be used.

## Actual results

The first matching block is used.

### PR DESCRIPTION
**Pull request by core23**
## Subject

I am targeting this branch, because this feature is BC.

Closes #194

## Changelog

```markdown
### Added
- Added `priority` to `sonata.breadcrumb` tag
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]
Imo will be nice to move knp_menu arguments to tag compiler instead using it as arguments.

**Comment by core23** [comment]
> Imo will be nice to move knp_menu arguments to tag compiler instead using it as arguments.

You mean this one?

```xml
        <argument type="service" id="knp_menu.menu_provider"/>
        <argument type="service" id="knp_menu.factory"/>
```

It's not possible, because it depends on the constructor parameter order.

**Comment by VincentLanglet** [comment]
Thanks

**Comment by wbloszyk** [comment]
> > Imo will be nice to move knp_menu arguments to tag compiler instead using it as arguments.
> 
> You mean this one?
> 
> ```
>         <argument type="service" id="knp_menu.menu_provider"/>
>         <argument type="service" id="knp_menu.factory"/>
> ```
> 
> It's not possible, because it depends on the constructor parameter order.

I know but we can change it in unstable branch.

**Comment by core23** [comment]
> I know but we can change it in unstable branch.

We should not enforce this, because a custom breadcrumb can change the parameter order in the constructor.

**Pull request merged**
